// Original supplemental Svelte DOM boundary only. Complete Source user fixture,
// real component state, injected API callbacks; no session, credential or HTTP issuance.
import { afterEach, expect, it, vi } from 'vitest';
import { mount, flushSync, tick, unmount } from 'svelte';
import UsersPage from '../../src/lib/users/UsersPage.svelte';
import { makeUser } from '../helpers/full-auth/user-fixture.ts';
import type { UsersClient } from '../../src/lib/users/types.ts';
const mounted: ReturnType<typeof mount>[] = [];
afterEach(async () => { for (const instance of mounted.splice(0)) await unmount(instance); document.body.replaceChildren(); });
async function settle() { await tick(); await Promise.resolve(); await tick(); }
function button(label: string) { return [...document.querySelectorAll<HTMLButtonElement>('button')].find(item => item.textContent?.trim() === label || item.getAttribute('aria-label') === label); }
async function change(label: string, value: string) { const input = document.querySelector<HTMLInputElement | HTMLSelectElement>(`[aria-label="${label}"]`); expect(input).not.toBeNull(); input!.value = value; input!.dispatchEvent(new Event(input!.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true })); await settle(); }
async function render(overrides: Partial<UsersClient> = {}) {
 const client = { fetchUsers: vi.fn().mockResolvedValue({ items: [makeUser()] }), fetchUser: vi.fn().mockResolvedValue(makeUser()), updateUser: vi.fn().mockResolvedValue(undefined), disableUser: vi.fn().mockResolvedValue(undefined), enableUser: vi.fn().mockResolvedValue(undefined), sendRecoveryLink: vi.fn().mockResolvedValue(undefined), inviteUser: vi.fn().mockResolvedValue({success:true,message:'Invitation sent'}), ...overrides };
 const target = document.createElement('div'); document.body.append(target); mounted.push(flushSync(() => mount(UsersPage, { target, props: { client } }))); await settle(); return { client, target };
}
async function selectUser() { const row = button('Test User'); expect(row).toBeDefined(); row!.click(); await settle(); }
it('lists complete stored profile status, role, login and passkey count', async () => { const { target }=await render(); expect(target.textContent).toContain('Test User');expect(target.textContent).toContain('test@example.com');expect(target.textContent).toContain('Author');expect(target.textContent).toContain('Active');expect(document.querySelector('table')).not.toBeNull(); });
it('initial pending query exposes loading without invented users', async () => { const { target }=await render({fetchUsers:vi.fn(()=>new Promise(()=>{}))});expect(target.textContent).toContain('Loading...');expect(target.textContent).not.toContain('Test User'); });
it('list failure exposes original error and retry reaches the actual callback', async () => { const fetchUsers=vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue({items:[makeUser()]}); const { target }=await render({fetchUsers});expect(target.textContent).toContain('Failed to load users: offline');expect(button('Try again')).toBeDefined();button('Try again')!.click();await settle();expect(fetchUsers).toHaveBeenCalledTimes(2);expect(target.textContent).toContain('Test User'); });
it('search uses the Source 300ms debounce and empty search is omitted', async () => { const {client}=await render();await change('Search users','test');expect(client.fetchUsers).toHaveBeenCalledTimes(1);await vi.waitFor(()=>expect(client.fetchUsers).toHaveBeenLastCalledWith({search:'test',role:undefined,cursor:undefined}),{timeout:1000}); });
it('role filter sends genuine role level and All roles clears it', async () => { const {client}=await render();await change('Filter by role','50');expect(client.fetchUsers).toHaveBeenLastCalledWith({search:undefined,role:50,cursor:undefined});await change('Filter by role','all');expect(client.fetchUsers).toHaveBeenLastCalledWith({search:undefined,role:undefined,cursor:undefined}); });
it('empty filter result can clear both filters', async () => { const {client,target}=await render({fetchUsers:vi.fn().mockResolvedValue({items:[]})});await change('Filter by role','40');expect(target.textContent).toContain('No users found matching your filters.');button('Clear filters')!.click();await settle();expect(document.querySelector<HTMLSelectElement>('[aria-label="Filter by role"]')?.value).toBe('all');expect(client.fetchUsers).toHaveBeenLastCalledWith({search:undefined,role:undefined,cursor:undefined}); });
it('load more uses returned cursor and appends the next whole user projection', async () => { const fetchUsers=vi.fn().mockResolvedValueOnce({items:[makeUser()],nextCursor:'user-1'}).mockResolvedValueOnce({items:[makeUser({id:'user-2',name:'Other User'})]});const {target}=await render({fetchUsers});button('Load More')!.click();await settle();expect(fetchUsers).toHaveBeenLastCalledWith({search:undefined,role:undefined,cursor:'user-1'});expect(target.textContent).toContain('Test User');expect(target.textContent).toContain('Other User');expect(button('Load More')).toBeUndefined(); });
it('selecting user calls real detail callback and unchanged Source caller supplies no self identity', async () => { const {client}=await render();await selectUser();expect(client.fetchUser).toHaveBeenCalledWith('user-1');expect(document.querySelector('[aria-label="Name"]')).not.toBeNull();expect(button('Disable')).toBeDefined(); });
it('promotion saves directly then refetches canonical detail metadata', async () => { const {client}=await render();await selectUser();await change('Role','40');button('Save Changes')!.click();await settle();expect(client.updateUser).toHaveBeenCalledWith('user-1',{role:40});expect(client.fetchUser).toHaveBeenCalledTimes(2); });
it('demotion requires confirmation and cancel preserves the pending account', async () => { const {client,target}=await render({fetchUser:vi.fn().mockResolvedValue(makeUser({role:50}))});await selectUser();await change('Role','30');button('Save Changes')!.click();await settle();expect(client.updateUser).not.toHaveBeenCalled();expect(target.textContent).toContain('Demote User?');button('Cancel')!.click();await settle();expect(client.updateUser).not.toHaveBeenCalled();expect(target.textContent).not.toContain('Demote User?'); });
it('confirmed demotion forwards only edited fields and server error stays in confirmation', async () => { const {client,target}=await render({fetchUser:vi.fn().mockResolvedValue(makeUser({role:50})),updateUser:vi.fn().mockRejectedValue(new Error('Cannot demote the last admin. Promote another user first.'))});await selectUser();await change('Role','30');button('Save Changes')!.click();await settle();button('Demote User')!.click();await settle();expect(client.updateUser).toHaveBeenCalledWith('user-1',{role:30});expect(target.textContent).toContain('Cannot demote the last admin. Promote another user first.'); });
it('disable waits for confirmation and successful callback refreshes list and detail', async () => { const {client,target}=await render();await selectUser();button('Disable')!.click();await settle();expect(client.disableUser).not.toHaveBeenCalled();expect(target.textContent).toContain('Disable User?');button('Disable User')!.click();await settle();expect(client.disableUser).toHaveBeenCalledWith('user-1');expect(client.fetchUser).toHaveBeenCalledTimes(2);expect(target.textContent).not.toContain('Disable User?'); });
it('disabled user enables directly and recovery feedback preserves server errors', async () => { const {client,target}=await render({fetchUser:vi.fn().mockResolvedValue(makeUser({disabled:true})),sendRecoveryLink:vi.fn().mockRejectedValue(new Error('Email provider unavailable'))});await selectUser();button('Enable')!.click();await settle();expect(client.enableUser).toHaveBeenCalledWith('user-1');button('Send Recovery Link')!.click();await settle();expect(client.sendRecoveryLink).toHaveBeenCalledWith('user-1');expect(target.textContent).toContain('Email provider unavailable'); });
it('invitation default Author body reaches callback and failure stays visible', async () => { const {client,target}=await render({inviteUser:vi.fn().mockRejectedValue(new Error('Already invited'))});button('Invite User')!.click();await settle();await change('Email address','new@example.com');button('Send Invite')!.click();await settle();expect(client.inviteUser).toHaveBeenCalledWith('new@example.com',30);expect(target.textContent).toContain('Already invited'); });
it('invitation copy-link fallback exposes actual callback URL while emailed invitation closes', async () => { const {target}=await render({inviteUser:vi.fn().mockResolvedValue({success:true,message:'Created',inviteUrl:'https://example.com/invite?token=abc'})});button('Invite User')!.click();await settle();await change('Email address','new@example.com');button('Send Invite')!.click();await settle();expect(target.textContent).toContain('Invite Link Created');expect(document.querySelector<HTMLInputElement>('[aria-label="Invite link"]')?.value).toBe('https://example.com/invite?token=abc'); });
