// Supplemental Native production-boundary controls, whole production Source audit.
// Pure controlled clients/timers only: zero original Source callbacks or HTTP credit.
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {QueryClient,type QueryObserverOptions} from '@tanstack/react-query';
import {calendarEditedState,calendarInitialLoading,calendarMenuOpenTarget,calendarTabTarget,createCalendarHoverTiming,createCalendarTooltipGroup,createCalendarTypeahead} from '../src/lib/calendar/presentation.ts';
import {runCalendarPanelAction,runCalendarReschedule} from '../src/lib/calendar/panel-actions.ts';
import {createCalendarRangeOwner,type CalendarRangeOptions} from '../src/lib/calendar/range-owner.ts';
import {observeCalendarMetadata} from '../src/lib/calendar/metadata-owner.ts';
import type {CalendarItem} from '../src/lib/calendar/calendar.ts';
import type {CalendarClient,CalendarManifest,CalendarUser} from '../src/lib/calendar/ui-types.ts';

beforeEach(()=>vi.useFakeTimers());afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();});
describe('Source pending presentation',()=>{
  it.each([[true,true,true],[false,true,false],[true,false,false],[false,false,false]])('pending=%s fetching=%s loading=%s',(pending,fetching,loading)=>{expect(calendarInitialLoading(pending,fetching)).toBe(loading);});
  it('distinguishes pending details from unavailable settled details',()=>{expect(calendarEditedState(true,false)).toBe('pending');expect(calendarEditedState(false,false)).toBe('unavailable');expect(calendarEditedState(false,true)).toBe('value');});
});
describe('Source view tabs and filter menu focus',()=>{
  it.each([['ArrowRight',0,2,'ltr',1],['ArrowRight',1,2,'ltr',0],['ArrowLeft',0,2,'ltr',1],['ArrowRight',0,2,'rtl',1],['Home',1,2,'ltr',0],['End',0,2,'ltr',1]] as const)('moves %s from%s', (key,current,count,dir,target)=>{expect(calendarTabTarget(key,current,count,dir)).toBe(target);});
  it('reserves Enter/Space activation and vertical arrows for their native owner',()=>{for(const key of ['Enter',' ','ArrowUp','ArrowDown'])expect(calendarTabTarget(key,0,2)).toBeUndefined();});
  it('opens ArrowUp at the last option including clear filters',()=>{expect(calendarMenuOpenTarget('ArrowUp',8)).toBe(7);});
  it('opens pointer/ArrowDown/Enter at the first option',()=>{for(const key of ['','ArrowDown','Enter'])expect(calendarMenuOpenTarget(key,8)).toBe(0);});
  it('uses case-insensitive consecutive prefix matches without activation',()=>{const search=createCalendarTypeahead();const labels=['Pages','Posts','Scheduled'];const event=(key:string)=>({key,ctrlKey:false,metaKey:false,altKey:false});expect(search.key(event('S'),labels,0)).toBe(2);expect(search.key(event('c'),labels,2)).toBe(2);});
  it('cycles repeated first characters after the current item',()=>{const search=createCalendarTypeahead(),event={key:'p',ctrlKey:false,metaKey:false,altKey:false};const labels=['Pages','Posts','Published'];expect(search.key(event,labels,0)).toBe(1);expect(search.key(event,labels,1)).toBe(2);});
  it('resets prefix after 500ms and ignores shortcut modifiers',()=>{const search=createCalendarTypeahead(),labels=['Pages','Posts','Scheduled'];const event=(key:string)=>({key,ctrlKey:false,metaKey:false,altKey:false});expect(search.key(event('p'),labels,0)).toBe(1);vi.advanceTimersByTime(500);expect(search.key(event('s'),labels,1)).toBe(2);expect(search.key({...event('p'),ctrlKey:true},labels,2)).toBeUndefined();});
});
describe('Source month tooltip rest and shared warm group',()=>{
  it('does not open on cold pointer entry without mouse movement',()=>{const show=vi.fn(),hover=createCalendarHoverTiming(show,vi.fn(),createCalendarTooltipGroup(400));hover.enter('mouse');vi.advanceTimersByTime(900);expect(show).not.toHaveBeenCalled();});
  it('opens after 400ms rest following mouse movement',()=>{const show=vi.fn(),hover=createCalendarHoverTiming(show,vi.fn(),createCalendarTooltipGroup(400));hover.enter('mouse');hover.move('mouse',2,0);vi.advanceTimersByTime(399);expect(show).not.toHaveBeenCalled();vi.advanceTimersByTime(1);expect(show).toHaveBeenCalledOnce();});
  it('restarts the rest delay after significant mouse movement',()=>{const show=vi.fn(),hover=createCalendarHoverTiming(show,vi.fn(),createCalendarTooltipGroup(400));hover.enter('mouse');hover.move('mouse',3,0);vi.advanceTimersByTime(300);hover.move('mouse',2,0);vi.advanceTimersByTime(399);expect(show).not.toHaveBeenCalled();vi.advanceTimersByTime(1);expect(show).toHaveBeenCalledOnce();});
  it('keeps a pending rest timer for tiny subsequent mouse movement',()=>{const show=vi.fn(),hover=createCalendarHoverTiming(show,vi.fn(),createCalendarTooltipGroup(400));hover.enter('mouse');hover.move('mouse',2,0);vi.advanceTimersByTime(300);hover.move('mouse',1,0);vi.advanceTimersByTime(100);expect(show).toHaveBeenCalledOnce();});
  it('focus opens immediately and a subsequent chip hover closes the previous chip',()=>{const group=createCalendarTooltipGroup(400),firstShow=vi.fn(),firstHide=vi.fn(),secondShow=vi.fn();const first=createCalendarHoverTiming(firstShow,firstHide,group),second=createCalendarHoverTiming(secondShow,vi.fn(),group);first.focus();expect(firstShow).toHaveBeenCalledOnce();second.enter('mouse');expect(secondShow).toHaveBeenCalledOnce();expect(firstHide).toHaveBeenCalledOnce();});
  it('retains warm opening until 400ms after the active chip closes',()=>{const group=createCalendarTooltipGroup(400),show=vi.fn(),first=createCalendarHoverTiming(vi.fn(),vi.fn(),group),second=createCalendarHoverTiming(show,vi.fn(),group);first.focus();first.close();vi.advanceTimersByTime(399);second.enter('mouse');expect(show).toHaveBeenCalledOnce();});
  it('restores cold delay after the complete 400ms closed period',()=>{const group=createCalendarTooltipGroup(400),show=vi.fn(),first=createCalendarHoverTiming(vi.fn(),vi.fn(),group),second=createCalendarHoverTiming(show,vi.fn(),group);first.focus();first.close();vi.advanceTimersByTime(400);second.enter('mouse');vi.advanceTimersByTime(400);expect(show).not.toHaveBeenCalled();second.move('mouse',2,0);vi.advanceTimersByTime(400);expect(show).toHaveBeenCalledOnce();});
  it('pointer cancellation clears pending and touch does not start a tooltip',()=>{const show=vi.fn(),hover=createCalendarHoverTiming(show,vi.fn(),createCalendarTooltipGroup(400));hover.enter('mouse');hover.move('mouse',2,0);hover.cancel();vi.advanceTimersByTime(1000);hover.enter('touch');hover.move('touch',2,0);vi.advanceTimersByTime(1000);expect(show).not.toHaveBeenCalled();});
});

const item={collection:'posts',id:'entry',locale:'en',key:'posts:entry:en',title:'Scheduled draft'} as CalendarItem;
function controlledClient():CalendarClient{return {fetchContent:vi.fn(),publishContent:vi.fn(async()=>({})),unscheduleContent:vi.fn(async()=>({})),scheduleContent:vi.fn(async()=>({}))};}
describe('Source panel owns action pending separately from details errors',()=>{
  it('preserves details errors when a publication action starts and succeeds',async()=>{let detail='Could not load details';const client=controlledClient();await runCalendarPanelAction('publish',item,{client,current:()=>true,pending:vi.fn(),error:value=>detail=value??'',refresh:vi.fn(),success:vi.fn(),failure:vi.fn(),close:vi.fn()});expect(detail).toBe('Could not load details');});
  it('reports a rejected publication to notices without adding an inline action error',async()=>{let detail='Could not load details';const client=controlledClient();client.publishContent=vi.fn(async()=>{throw Error('Publication failed');});const failure=vi.fn();await runCalendarPanelAction('publish',item,{client,current:()=>true,pending:vi.fn(),error:value=>detail=value??'',refresh:vi.fn(),success:vi.fn(),failure,close:vi.fn()});expect(detail).toBe('Could not load details');expect(failure).toHaveBeenCalledWith('Publication failed');});
  it.each([null,undefined,false,0,''])('keeps notice title but suppresses falsy rejection description %s',async cause=>{const client=controlledClient(),failure=vi.fn(),genericError=vi.fn(()=> 'Translated generic');client.publishContent=vi.fn(async()=>{throw cause;});await runCalendarPanelAction('publish',item,{client,current:()=>true,pending:vi.fn(),error:vi.fn(),refresh:vi.fn(),success:vi.fn(),failure,genericError,close:vi.fn()});expect(failure).toHaveBeenCalledWith(null);expect(genericError).not.toHaveBeenCalled();});
  it.each(['raw cause',123,{reason:'non-Error'}])('uses caller-owned Source generic descriptor for truthy non-Error %s',async cause=>{const client=controlledClient(),failure=vi.fn(),genericError=vi.fn(()=> 'Translated generic');client.publishContent=vi.fn(async()=>{throw cause;});await runCalendarPanelAction('publish',item,{client,current:()=>true,pending:vi.fn(),error:vi.fn(),refresh:vi.fn(),success:vi.fn(),failure,genericError,close:vi.fn()});expect(failure).toHaveBeenCalledWith('Translated generic');expect(genericError).toHaveBeenCalledOnce();});
  it('retains an empty Error message without a generic replacement',async()=>{const client=controlledClient(),failure=vi.fn(),genericError=vi.fn(()=> 'Translated generic');client.publishContent=vi.fn(async()=>{throw Error('');});await runCalendarPanelAction('publish',item,{client,current:()=>true,pending:vi.fn(),error:vi.fn(),refresh:vi.fn(),success:vi.fn(),failure,genericError,close:vi.fn()});expect(failure).toHaveBeenCalledWith('');expect(genericError).not.toHaveBeenCalled();});
  it('retains panel pending for the whole controlled reschedule promise',async()=>{let complete!:()=>void;const client=controlledClient();client.scheduleContent=vi.fn(()=>new Promise<void>(resolve=>complete=resolve));let pending=false;const operation=runCalendarReschedule(item,'2026-11-01T10:00:00Z',{client,pending:value=>pending=value,current:()=>true,refresh:vi.fn(),success:vi.fn(),rescheduled:vi.fn()});expect(pending).toBe(true);complete();await operation;expect(pending).toBe(false);});
  it('clears panel pending after a rejected controlled reschedule',async()=>{const client=controlledClient(),pending=vi.fn();client.scheduleContent=vi.fn(async()=>{throw Error('Schedule failed');});await expect(runCalendarReschedule(item,'2026-11-01T10:00:00Z',{client,pending,current:()=>true,refresh:vi.fn(),success:vi.fn(),rescheduled:vi.fn()})).rejects.toThrow('Schedule failed');expect(pending.mock.calls).toEqual([[true],[false]]);});
});
describe('Source metadata observes the existing QueryClient',()=>{
  const initialManifest:CalendarManifest={timezone:'UTC',collections:{posts:{label:'Posts'}}};
  const initialUser:CalendarUser={id:'reader',email:'reader@example.invalid',role:10};
  it('refreshes display settings through the existing manifest query',async()=>{const client=new QueryClient({defaultOptions:{queries:{staleTime:60000,retry:1}}}),apply=vi.fn();const updated={...initialManifest,timezone:'Europe/Paris'};const readers={fetchManifest:vi.fn(async()=>updated),fetchCurrentUser:vi.fn(async()=>initialUser)};const owner=observeCalendarMetadata(client,readers,{manifest:initialManifest,user:initialUser},apply);try{await expect(owner.refetchManifest()).resolves.toEqual(updated);expect(apply.mock.calls.at(-1)?.[0].manifest).toEqual(updated);expect(client.getQueryData(['manifest'])).toEqual(updated);}finally{owner.destroy();client.clear();}});
  it('refreshes user affordances under the exact Source currentUser key and options',async()=>{const client=new QueryClient({defaultOptions:{queries:{staleTime:60000,retry:1}}}),apply=vi.fn(),updated={...initialUser,role:40};const owner=observeCalendarMetadata(client,{fetchManifest:vi.fn(async()=>initialManifest),fetchCurrentUser:vi.fn(async()=>updated)},{manifest:initialManifest,user:initialUser},apply);try{await expect(owner.refetchUser()).resolves.toEqual(updated);expect(apply.mock.calls.at(-1)?.[0].user).toEqual(updated);const query=client.getQueryCache().find({queryKey:['currentUser']});expect((query?.options as QueryObserverOptions<CalendarUser|null>|undefined)?.staleTime).toBe(300000);expect(query?.options.retry).toBe(false);}finally{owner.destroy();client.clear();}});
});

describe('Source range observer survives metadata-only changes',()=>{
  it('retains a settled terminal error without fetching again for changed manifest labels',async()=>{const client=new QueryClient({defaultOptions:{queries:{retry:false}}}),fetch=vi.fn(async()=>{throw Error('Range failed');}),owner=createCalendarRangeOwner(vi.fn(),vi.fn());const options={queryKey:['calendar','2026-10-01','2026-11-01'],queryFn:fetch,staleTime:0,retry:false} as CalendarRangeOptions;try{owner.update(client,{label:'Posts'},options);await owner.refetch();expect(fetch).toHaveBeenCalledOnce();owner.update(client,{label:'Articles'},options);expect(fetch).toHaveBeenCalledOnce();}finally{owner.destroy();client.clear();}});
  it('creates the new Source range observer for actual key changes',async()=>{const client=new QueryClient({defaultOptions:{queries:{retry:false}}}),fetch=vi.fn(async()=>({items:[],truncated:false})),owner=createCalendarRangeOwner(vi.fn(),vi.fn());const options={queryKey:['calendar','2026-10-01','2026-11-01'],queryFn:fetch,staleTime:0,retry:false} as CalendarRangeOptions;try{owner.update(client,{},options);await owner.refetch();owner.update(client,{}, {...options,queryKey:['calendar','2026-11-01','2026-12-01']});await owner.refetch();expect(fetch).toHaveBeenCalledTimes(2);}finally{owner.destroy();client.clear();}});
  it('does not warm the provider for a row whose production show operation declines',()=>{const group=createCalendarTooltipGroup(400),row=createCalendarHoverTiming(()=>false,vi.fn(),group);row.focus();expect(group.delay()).toBe(400);});
  it('keeps a dismissed tooltip closed during mouse movement until pointer re-entry',()=>{const group=createCalendarTooltipGroup(400),show=vi.fn(),hover=createCalendarHoverTiming(show,vi.fn(),group);hover.enter('mouse');hover.focus();hover.close();vi.advanceTimersByTime(400);hover.move('mouse',2,0);vi.advanceTimersByTime(400);expect(show).toHaveBeenCalledOnce();hover.enter('mouse');hover.move('mouse',2,0);vi.advanceTimersByTime(400);expect(show).toHaveBeenCalledTimes(2);});
});
