import test from 'node:test';
import assert from 'node:assert/strict';
import {sql} from 'kysely';
import {openSqlite} from '../src/lib/server/database/sqlite.ts';
import {migrateCms} from '../src/lib/server/database/migrations.ts';
import {SchemaRegistry} from '../src/lib/server/database/registry.ts';
import {lifecycleService} from '../src/lib/server/database/lifecycle/service.ts';
import {NativeTaxonomyRepository} from '../src/lib/server/taxonomies/upstream/database/repositories/taxonomy-native.ts';
import {registerTaxonomyDatabase} from '../src/lib/server/taxonomies/upstream/host.ts';
const principal={id:'author',permissions:['content:create','content:read','content:read_drafts','content:edit_any'] as any};
async function fixture(revisions=false){const database=openSqlite(':memory:');await migrateCms(database);registerTaxonomyDatabase(database);const registry=new SchemaRegistry(database);await registry.createCollection({slug:'posts',label:'Posts',supports:revisions?['revisions']:[]});await registry.createField('posts',{slug:'title',label:'Title',type:'string'});const repo=new NativeTaxonomyRepository(database.db as any);const old=await repo.create({name:'tag',slug:'old',label:'Old'}),next=await repo.create({name:'tag',slug:'next',label:'Next'});return{database,repo,old,next,service:lifecycleService(database,principal)};}
async function rejectNext(value:Awaited<ReturnType<typeof fixture>>){await sql`CREATE TRIGGER reject_new_term BEFORE INSERT ON content_taxonomies WHEN NEW.taxonomy_id=${sql.lit(value.next.translationGroup!)} BEGIN SELECT RAISE(ABORT,'assignment failure'); END`.execute(value.database.db);}
test('taxonomy create and content insert roll back together on an actual SQL assignment failure',async()=>{const f=await fixture();try{await rejectNext(f);await assert.rejects(f.service.createContent({type:'posts',data:{title:'Rollback'},slug:'rollback',taxonomies:{tag:['next']}}),/assignment failure/);assert.equal((await sql`SELECT id FROM ec_posts WHERE slug='rollback'`.execute(f.database.db)).rows.length,0);}finally{await f.database.close();}});
for(const revisions of [false,true])test(`mixed content/taxonomy failure rolls back content and revision writes (revisions=${revisions})`,async()=>{const f=await fixture(revisions);try{const item=await f.service.createContent({type:'posts',data:{title:'Original'}});await f.repo.setTermsForEntry('posts',item.id,'tag',[f.old.id]);await rejectNext(f);await assert.rejects(f.service.updateContent({type:'posts',id:item.id,data:{title:'Changed'},taxonomies:{tag:['next']},expected:{version:item.version,updatedAt:item.updatedAt}}),/assignment failure/);const stored=await f.service.getContent({type:'posts',id:item.id});assert.equal(stored.data.title,'Original');assert.equal(stored.version,item.version);assert.equal(stored.draftRevisionId,item.draftRevisionId);assert.deepEqual((await f.repo.getTermsForEntry('posts',item.id,'tag')).map(term=>term.slug),['old']);assert.equal((await sql`SELECT id FROM _cms_revisions WHERE entry_id=${item.id}`.execute(f.database.db)).rows.length,0);}finally{await f.database.close();}});
test('term-only updates preserve scalar revision token and metadata',async()=>{const f=await fixture(true);try{const item=await f.service.createContent({type:'posts',data:{title:'Original'}});const receipt=await f.service.setContentTaxonomies({type:'posts',id:item.id,taxonomies:{tag:['old']}});assert.equal(receipt.item.version,item.version);assert.equal(receipt.item.updatedAt,item.updatedAt);assert.equal(receipt.item.draftRevisionId,item.draftRevisionId);assert.equal(receipt.liveContentChanged,false);assert.deepEqual((await f.repo.getTermsForEntry('posts',item.id,'tag')).map(term=>term.slug),['old']);}finally{await f.database.close();}});
test('a stale mutation cannot commit taxonomy effects while its content CAS updates zero rows',async()=>{const f=await fixture();try{const item=await f.service.createContent({type:'posts',data:{title:'Original'}});const original=f.database.atomicBatch.bind(f.database);let intercepted=false;f.database.atomicBatch=async statements=>{if(!intercepted&&statements.some(query=>query.sql.includes('content_taxonomies'))){intercepted=true;await sql`UPDATE ec_posts SET version=version+1 WHERE id=${item.id}`.execute(f.database.db);}return original(statements);};await assert.rejects(f.service.updateContent({type:'posts',id:item.id,data:{title:'Changed'},taxonomies:{tag:['old']},expected:{version:item.version,updatedAt:item.updatedAt}}),{code:'CONFLICT'});assert.deepEqual(await f.repo.getTermsForEntry('posts',item.id,'tag'),[]);assert.equal((await f.service.getContent({type:'posts',id:item.id})).data.title,'Original');}finally{await f.database.close();}});
