import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button, Loader, Select } from "@cloudflare/kumo";
import { useLingui } from "@lingui/react/macro";
import { UserPlus, Prohibit, CheckCircle } from "@phosphor-icons/react";
import * as React from "react";
import { cn } from "../../lib/utils";
import { TableToolbar, TableToolbarSearch } from "../TableToolbar.js";
import { RoleBadge } from "./RoleBadge";
import { useRolesConfig } from "./useRolesConfig.js";
/**
 * User list component with search, filter, and table display
 */
export function UserList({ users, isLoading, hasMore, searchQuery, roleFilter, onSearchChange, onRoleFilterChange, onSelectUser, onInviteUser, onLoadMore, }) {
    const { t } = useLingui();
    const { roles, roleLabels } = useRolesConfig();
    const roleFilterSelectItems = React.useMemo(() => ({ all: t `All roles`, ...roleLabels }), [t, roleLabels]);
    const roleFilterSelectOptions = React.useMemo(() => [{ value: "all", label: t `All roles` }, ...roles], [t, roles]);
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h1", { className: "text-2xl font-semibold leading-tight", children: t `Users` }), _jsx(Button, { onClick: onInviteUser, icon: _jsx(UserPlus, {}), children: t `Invite User` })] }), _jsxs(TableToolbar, { children: [_jsx(TableToolbarSearch, { placeholder: t `Search by name or email...`, value: searchQuery, onChange: (e) => onSearchChange(e.target.value), "aria-label": t `Search users` }), _jsx(Select, { size: "sm", value: roleFilter?.toString() ?? "all", onValueChange: (value) => onRoleFilterChange(value === "all" || value === null ? undefined : parseInt(value, 10)), items: roleFilterSelectItems, "aria-label": t `Filter by role`, children: roleFilterSelectOptions.map((option) => (_jsx(Select.Option, { value: option.value, children: option.label }, option.value))) })] }), _jsx("div", { className: "rounded-md border bg-kumo-base overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b bg-kumo-tint/50", children: [_jsx("th", { scope: "col", className: "px-4 py-3 text-start text-sm font-medium", children: t `User` }), _jsx("th", { scope: "col", className: "px-4 py-3 text-start text-sm font-medium", children: t `Role` }), _jsx("th", { scope: "col", className: "px-4 py-3 text-start text-sm font-medium", children: t `Status` }), _jsx("th", { scope: "col", className: "px-4 py-3 text-start text-sm font-medium", children: t `Last Login` }), _jsx("th", { scope: "col", className: "px-4 py-3 text-start text-sm font-medium", children: t `Passkeys` })] }) }), _jsxs("tbody", { className: "divide-y divide-kumo-line", children: [users.length === 0 && !isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-4 py-8 text-center text-kumo-subtle", children: searchQuery || roleFilter !== undefined ? (_jsxs(_Fragment, { children: [t `No users found matching your filters.`, " ", _jsx("button", { type: "button", className: "text-kumo-link underline", onClick: () => {
                                                        onSearchChange("");
                                                        onRoleFilterChange(undefined);
                                                    }, children: t `Clear filters` })] })) : (_jsxs(_Fragment, { children: [t `No users yet.`, " ", _jsx("button", { type: "button", className: "text-kumo-link underline", onClick: onInviteUser, children: t `Invite your first team member` })] })) }) })) : (users.map((user) => (_jsx(UserListRow, { user: user, onSelect: () => onSelectUser(user.id) }, user.id)))), isLoading && (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-4 py-4", children: _jsxs("div", { className: "flex items-center justify-center gap-2 text-kumo-subtle", children: [_jsx(Loader, { size: "sm" }), t `Loading...`] }) }) }))] })] }) }), hasMore && !isLoading && (_jsx("div", { className: "flex justify-center", children: _jsx(Button, { variant: "outline", onClick: onLoadMore, children: t `Load More` }) }))] }));
}
function UserListRow({ user, onSelect }) {
    const displayName = user.name || user.email;
    const { t } = useLingui();
    const lastLogin = user.lastLogin ? new Date(user.lastLogin).toLocaleDateString() : t `Never`;
    return (_jsxs("tr", { className: "hover:bg-kumo-tint/25 cursor-pointer", onClick: onSelect, children: [_jsx("td", { className: "px-4 py-3", children: _jsxs("div", { className: "flex items-center gap-3", children: [user.avatarUrl ? (_jsx("img", { src: user.avatarUrl, alt: "", className: "h-8 w-8 rounded-full object-cover" })) : (_jsx("div", { className: "h-8 w-8 rounded-full bg-kumo-tint flex items-center justify-center text-sm font-medium", children: (user.name || user.email)?.[0]?.toUpperCase() ?? "?" })), _jsxs("div", { children: [_jsx("div", { className: "font-medium", children: displayName }), user.name && _jsx("div", { className: "text-sm text-kumo-subtle", children: user.email })] })] }) }), _jsx("td", { className: "px-4 py-3", children: _jsx(RoleBadge, { role: user.role }) }), _jsx("td", { className: "px-4 py-3", children: user.disabled ? (_jsxs("span", { className: "inline-flex items-center gap-1 text-sm text-kumo-danger", children: [_jsx(Prohibit, { className: "h-3.5 w-3.5", "aria-hidden": "true" }), t `Disabled`] })) : (_jsxs("span", { className: "inline-flex items-center gap-1 text-sm text-kumo-success", children: [_jsx(CheckCircle, { className: "h-3.5 w-3.5", "aria-hidden": "true" }), t `Active`] })) }), _jsx("td", { className: "px-4 py-3 text-sm text-kumo-subtle", children: lastLogin }), _jsx("td", { className: "px-4 py-3", children: _jsx("span", { className: cn("text-sm", user.credentialCount === 0 && "text-kumo-subtle"), children: user.credentialCount }) })] }));
}
/** Loading skeleton for user list */
export function UserListSkeleton() {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "h-8 w-24 bg-kumo-tint animate-pulse rounded" }), _jsx("div", { className: "h-10 w-32 bg-kumo-tint animate-pulse rounded" })] }), _jsxs("div", { className: "flex gap-4", children: [_jsx("div", { className: "h-10 w-64 bg-kumo-tint animate-pulse rounded" }), _jsx("div", { className: "h-10 w-44 bg-kumo-tint animate-pulse rounded" })] }), _jsxs("div", { className: "rounded-md border bg-kumo-base", children: [_jsx("div", { className: "border-b bg-kumo-tint/50 px-4 py-3", children: _jsx("div", { className: "h-4 w-full bg-kumo-tint animate-pulse rounded" }) }), _jsx("div", { className: "divide-y divide-kumo-line", children: Array.from({ length: 5 }, (_, i) => (_jsx("div", { className: "px-4 py-4", children: _jsx("div", { className: "h-8 w-full bg-kumo-tint animate-pulse rounded" }) }, i))) })] })] }));
}
