// Actual Native domain constructors on the same registered owner. Node Source
// provider identities remain in providers.ts without D1 substitutions.
export * from './providers.ts';
import type {Kysely} from 'kysely';
import type {Database} from './upstream/database/types.ts';
import {seedNativeBylines,seedNativeTaxonomies,seedNativeRelations,seedNativeMedia,seedNativeRedirects,seedNativeFts,seedNativeBlocks,seedNativeMediaUsage,seedNativeMarkMediaStale,seedNativeMarkMediaStaleSafely} from './namespace.ts';
import {BylineRepository as Byline} from '../bylines/repository.ts';
import {TaxonomyRepository as Taxonomy} from '../taxonomies/repository.ts';
import {RelationRepository as Relation} from '../relations/repository.ts';
import {MediaRepository as Media} from '../general-media/index.ts';
import {RedirectRepository as Redirect} from '../redirects/repository.ts';
import {FTSManager as FTS} from '../content-picker/fts-manager.ts';
import {BlockTypeRegistry as Block} from '../blocks/upstream/schema/block-type-registry.ts';
import {MediaUsageRepository as Usage} from './d1-media-usage.ts';
export const BylineRepository=function(db:Kysely<Database>){return seedNativeBylines(db);} as unknown as new(db:Kysely<Database>)=>Byline;
export type BylineRepository=Byline;
export const TaxonomyRepository=function(db:Kysely<Database>){return seedNativeTaxonomies(db);} as unknown as new(db:Kysely<Database>)=>Taxonomy;
export type TaxonomyRepository=Taxonomy;
export const RelationRepository=function(db:Kysely<Database>){return seedNativeRelations(db);} as unknown as new(db:Kysely<Database>)=>Relation;
export const MediaRepository=function(db:Kysely<Database>){return seedNativeMedia(db);} as unknown as new(db:Kysely<Database>)=>Media;
export type MediaRepository=Media;
export const RedirectRepository=function(db:Kysely<Database>){return seedNativeRedirects(db);} as unknown as new(db:Kysely<Database>)=>Redirect;
export type RedirectRepository=Redirect;
export const FTSManager=function(db:Kysely<Database>){return seedNativeFts(db);} as unknown as new(db:Kysely<Database>)=>FTS;
export type FTSManager=FTS;
export const BlockTypeRegistry=function(db:Kysely<Database>){return seedNativeBlocks(db);} as unknown as new(db:Kysely<Database>)=>Block;
export type BlockTypeRegistry=Block;
export const MediaUsageRepository=function(db:Kysely<Database>){return seedNativeMediaUsage(db);} as unknown as new(db:Kysely<Database>)=>Usage;
export type MediaUsageRepository=Usage;
export const markContentMediaUsageCollectionStale=seedNativeMarkMediaStale;
export const markContentMediaUsageCollectionStaleSafely=seedNativeMarkMediaStaleSafely;
