// Original supplemental transport tests. fetch is controlled; no authenticated HTTP.
import { test } from 'vitest';
import assert from 'node:assert/strict';
import { createUsersClient } from '../../src/lib/users/client.ts';
import { makeUser } from '../helpers/full-auth/user-fixture.ts';
function transport(responses:Response[]){const calls:{url:string;init?:RequestInit}[]=[];const fetcher:typeof fetch=async(input,init)=>{calls.push({url:String(input),init});const response=responses.shift();assert.ok(response,'whole supplied response fixture');return response;};return {client:createUsersClient('/cms',fetcher),calls};}
const success=(data:unknown)=>Response.json({success:true,data});
test('users client preserves exact Source filters and framework base path',async()=>{const {client,calls}=transport([success({items:[makeUser()],nextCursor:'user-1'})]);const page=await client.fetchUsers({search:'Test User',role:30,cursor:'user-1',limit:25});assert.equal(page.items[0].id,'user-1');assert.equal(calls[0].url,'/cms/api/admin/users?search=Test+User&role=30&cursor=user-1&limit=25');assert.equal(new Headers(calls[0].init?.headers).get('X-EmDash-Request'),'1');});
test('empty filters omit query and detail unwraps canonical item',async()=>{const {client,calls}=transport([success({items:[]}),success({item:makeUser()})]);await client.fetchUsers();assert.equal(calls[0].url,'/cms/api/admin/users');assert.equal((await client.fetchUser('user-1')).credentials[0].id,'cred-1');});
test('update sends only supplied fields and never claims returned profile contains detail metadata',async()=>{const {client,calls}=transport([success({item:{id:'user-1',name:'Changed'}})]);assert.deepEqual(await client.updateUser('user-1',{name:'Changed'}),{id:'user-1',name:'Changed'});assert.equal(calls[0].init?.method,'PUT');assert.equal(calls[0].init?.body,JSON.stringify({name:'Changed'}));assert.equal(new Headers(calls[0].init?.headers).get('Content-Type'),'application/json');});
test('enable disable and recovery preserve three Source POST routes',async()=>{const {client,calls}=transport([success({}),success({}),success({})]);await client.disableUser('user-1');await client.enableUser('user-1');await client.sendRecoveryLink('user-1');assert.deepEqual(calls.map(x=>x.url),['/cms/api/admin/users/user-1/disable','/cms/api/admin/users/user-1/enable','/cms/api/admin/users/user-1/send-recovery']);assert.ok(calls.every(x=>x.init?.method==='POST'));});
test('invitation preserves default omission and actual copy-link result',async()=>{const {client,calls}=transport([success({success:true,message:'Created',inviteUrl:'https://example.com/invite?token=abc'})]);const result=await client.inviteUser('new@example.com');assert.equal(calls[0].url,'/cms/api/auth/invite');assert.equal(calls[0].init?.body,JSON.stringify({email:'new@example.com'}));assert.equal(result.inviteUrl,'https://example.com/invite?token=abc');});
test('canonical API error code and field details reach caller',async()=>{const details={issues:[{path:'email',message:'Invalid email'},{path:'role',message:'Invalid role'}]};const {client}=transport([Response.json({success:false,error:{code:'VALIDATION_ERROR',message:'Invalid request data',details}},{status:400})]);await assert.rejects(client.inviteUser('bad',999),error=>{assert.equal((error as any).code,'VALIDATION_ERROR');assert.equal((error as any).status,400);assert.equal((error as Error).message,'email: Invalid email; role: Invalid role');assert.deepEqual((error as any).details,details);return true;});});
test('detail not found keeps Source caller-readable identity and malformed error uses fallback',async()=>{const {client}=transport([new Response('',{status:404}),new Response('not-json',{status:503,statusText:'Unavailable'})]);await assert.rejects(client.fetchUser('user-1'),{message:'User not found: user-1'});await assert.rejects(client.enableUser('user-1'),{message:'Failed to enable user: Unavailable'});});
