// Generated by the actual installed Lingui5.9.5 macro compiler from the whole pinned Source language module; no language values altered.
// Ported from EmDash1.1.0 913cb1bb9b7f08c3ff0d258b4420e53835b6a58e.
// Source: packages/admin/src/components/editor/codeBlockLanguages.ts; MIT, see notices/emdash-MIT.txt.

/**
 * Curated list of code block languages.
 *
 * Used as suggestions in the editor's language picker. The picker accepts
 * free-form text, so this is a starting point, not a restriction. The `id`
 * is the canonical identifier persisted in the Portable Text `language`
 * field and emitted as a `language-{id}` CSS class on the frontend.
 *
 * Aliases let common variants ("typescript", "ts") resolve to the same stored
 * id. Editor highlighters leave unsupported stored ids as plain text.
 */

import type { MessageDescriptor } from "@lingui/core";
export interface CodeBlockLanguage {
  /** Canonical identifier persisted in storage and emitted as `language-{id}`. */
  id: string;
  /** Human-readable label shown in the picker. */
  label: MessageDescriptor;
  /** Alternative identifiers (typed by the user) that resolve to this language. */
  aliases?: string[];
}
export const CODE_BLOCK_LANGUAGES: readonly CodeBlockLanguage[] = [{
  id: "plaintext",
  label:
  /*i18n*/
  {
    id: "pOo4Aa",
    message: "Plain text"
  },
  aliases: ["text", "plain", "txt"]
}, {
  id: "astro",
  label:
  /*i18n*/
  {
    id: "2qNhQ4",
    message: "Astro"
  }
}, {
  id: "bash",
  label:
  /*i18n*/
  {
    id: "DjECRV",
    message: "Bash"
  },
  aliases: ["sh", "shell", "zsh"]
}, {
  id: "c",
  label:
  /*i18n*/
  {
    id: "qvh3Th",
    message: "C"
  }
}, {
  id: "cpp",
  label:
  /*i18n*/
  {
    id: "ZfVDhL",
    message: "C++"
  },
  aliases: ["c++"]
}, {
  id: "csharp",
  label:
  /*i18n*/
  {
    id: "JMN/Cx",
    message: "C#"
  },
  aliases: ["cs", "c#"]
}, {
  id: "css",
  label:
  /*i18n*/
  {
    id: "Tfspdu",
    message: "CSS"
  }
}, {
  id: "diff",
  label:
  /*i18n*/
  {
    id: "bspG20",
    message: "Diff"
  },
  aliases: ["patch"]
}, {
  id: "dockerfile",
  label:
  /*i18n*/
  {
    id: "xbo2Nv",
    message: "Dockerfile"
  },
  aliases: ["docker"]
}, {
  id: "fsharp",
  label:
  /*i18n*/
  {
    id: "+4hbkZ",
    message: "F#"
  },
  aliases: ["f#", "fs"]
}, {
  id: "go",
  label:
  /*i18n*/
  {
    id: "4pSxwB",
    message: "Go"
  },
  aliases: ["golang"]
}, {
  id: "graphql",
  label:
  /*i18n*/
  {
    id: "gBiL6J",
    message: "GraphQL"
  },
  aliases: ["gql"]
}, {
  id: "html",
  label:
  /*i18n*/
  {
    id: "FBknns",
    message: "HTML"
  }
}, {
  id: "java",
  label:
  /*i18n*/
  {
    id: "d/bW+Y",
    message: "Java"
  }
}, {
  id: "javascript",
  label:
  /*i18n*/
  {
    id: "k8pHx9",
    message: "JavaScript"
  },
  aliases: ["js"]
}, {
  id: "json",
  label:
  /*i18n*/
  {
    id: "B2Zb/F",
    message: "JSON"
  }
}, {
  id: "jsx",
  label:
  /*i18n*/
  {
    id: "ijupPe",
    message: "JSX"
  }
}, {
  id: "kotlin",
  label:
  /*i18n*/
  {
    id: "ouqXGV",
    message: "Kotlin"
  },
  aliases: ["kt"]
}, {
  id: "lua",
  label:
  /*i18n*/
  {
    id: "zAp9SI",
    message: "Lua"
  }
}, {
  id: "markdown",
  label:
  /*i18n*/
  {
    id: "u6Hp4N",
    message: "Markdown"
  },
  aliases: ["md"]
}, {
  id: "mdx",
  label:
  /*i18n*/
  {
    id: "6TGIsL",
    message: "MDX"
  }
}, {
  id: "php",
  label:
  /*i18n*/
  {
    id: "Zw6ISu",
    message: "PHP"
  }
}, {
  id: "python",
  label:
  /*i18n*/
  {
    id: "zY6PMh",
    message: "Python"
  },
  aliases: ["py"]
}, {
  id: "ruby",
  label:
  /*i18n*/
  {
    id: "7jTlsu",
    message: "Ruby"
  },
  aliases: ["rb"]
}, {
  id: "rust",
  label:
  /*i18n*/
  {
    id: "Sc8PMh",
    message: "Rust"
  },
  aliases: ["rs"]
}, {
  id: "scss",
  label:
  /*i18n*/
  {
    id: "xEGQEX",
    message: "SCSS"
  },
  aliases: ["sass"]
}, {
  id: "sql",
  label:
  /*i18n*/
  {
    id: "mZT1Nu",
    message: "SQL"
  }
}, {
  id: "svelte",
  label:
  /*i18n*/
  {
    id: "I0X6aq",
    message: "Svelte"
  }
}, {
  id: "swift",
  label:
  /*i18n*/
  {
    id: "D8sGaA",
    message: "Swift"
  }
}, {
  id: "toml",
  label:
  /*i18n*/
  {
    id: "ZmWJqk",
    message: "TOML"
  }
}, {
  id: "tsx",
  label:
  /*i18n*/
  {
    id: "lFP3br",
    message: "TSX"
  }
}, {
  id: "typescript",
  label:
  /*i18n*/
  {
    id: "49rpnf",
    message: "TypeScript"
  },
  aliases: ["ts"]
}, {
  id: "vue",
  label:
  /*i18n*/
  {
    id: "M6Uejz",
    message: "Vue"
  }
}, {
  id: "xml",
  label:
  /*i18n*/
  {
    id: "8W/ILN",
    message: "XML"
  }
}, {
  id: "yaml",
  label:
  /*i18n*/
  {
    id: "h51QFW",
    message: "YAML"
  },
  aliases: ["yml"]
}, {
  id: "zig",
  label:
  /*i18n*/
  {
    id: "vt/0BC",
    message: "Zig"
  }
}];

/**
 * Look up a language by id or alias. Case-insensitive.
 * Returns the canonical entry, or `null` if not found in the curated list.
 */
export function findLanguage(value: string | null | undefined): CodeBlockLanguage | null {
  if (!value) return null;
  const searchText = value.trim().toLowerCase();
  if (!searchText) return null;
  for (const lang of CODE_BLOCK_LANGUAGES) {
    if (lang.id === searchText) return lang;
    if (lang.aliases?.includes(searchText)) return lang;
  }
  return null;
}

/**
 * Normalize a user-entered language string to a canonical id where possible.
 * Unknown inputs are sanitized to a single safe class token: lowercased,
 * trimmed, with any character outside `[a-z0-9_-]` (including whitespace,
 * dots, slashes, etc.) collapsed to `-`. This keeps the stored value safe
 * to interpolate into a `language-{id}` CSS class without splitting on
 * whitespace.
 *
 * Examples:
 *   normalizeLanguage("TypeScript")   -> "typescript" (canonical id)
 *   normalizeLanguage("ts")           -> "typescript" (alias)
 *   normalizeLanguage("Objective C")  -> "objective-c" (sanitized)
 *   normalizeLanguage("F#")           -> "fsharp" (canonical id)
 *   normalizeLanguage("")             -> undefined
 */
// Hoisted to module scope to avoid re-compilation on every call.
const DISALLOWED_CHARS_RE = /[^a-z0-9_-]+/g;
const LEADING_TRAILING_HYPHENS_RE = /^-+|-+$/g;
export function normalizeLanguage(value: string | null | undefined): string | undefined {
  if (!value) return undefined;
  const trimmed = value.trim();
  if (!trimmed) return undefined;
  const match = findLanguage(trimmed);
  if (match) return match.id;
  // Sanitize unknown input: lowercase, then collapse runs of disallowed
  // characters into a single `-` so the result is always a single CSS class
  // token. We deliberately don't return `undefined` on collisions here --
  // callers can compare the sanitized result with the input if they need to.
  const sanitized = trimmed.toLowerCase().replace(DISALLOWED_CHARS_RE, "-").replace(LEADING_TRAILING_HYPHENS_RE, "");
  return sanitized || undefined;
}

/**
 * Human-readable label for a stored language id. Falls back to the id itself
 * for unknown values so the editor never shows "undefined".
 */
export function languageLabelDescriptor(value: string | null | undefined): MessageDescriptor | string {
  if (!value) return /*i18n*/{
    id: "pOo4Aa",
    message: "Plain text"
  };
  const match = findLanguage(value);
  if (match) return match.label;
  return value;
}
