// Exact descriptor objects generated by actual Lingui5.9.5 from the three pinned Source footer plural calls.
export function footerMessages(words: number, characters: number, readingTime: number) {
 return [{
        id: "gqERK4",
        message: "{words, plural, one {# word} other {# words}}",
        values: {
          words: words
        }
      },
{
        id: "s6B3oh",
        message: "{characters, plural, one {# character} other {# characters}}",
        values: {
          characters: characters
        }
      },
{
        id: "d5ybJG",
        message: "{readingTime, plural, one {# min read} other {# min read}}",
        values: {
          readingTime: readingTime
        }
      }];
}
