// Original native DOM requirements derived from the whole pinned BulkTagDialog contract.
// No browser geometry, persisted API, or whole Source callback credit is claimed.
import {afterEach,expect,it,vi} from 'vitest';
import {flushSync,mount,tick,unmount} from 'svelte';
import Dialog from '../../src/lib/bulk-taxonomy/BulkTaxonomyDialog.svelte';
import Selection from '../../src/lib/bulk-taxonomy/BulkTaxonomySelection.svelte';
import type {BulkTaxonomyClient,BulkTaxonomyResult,BulkTaxonomyTerm} from '../../src/lib/bulk-taxonomy/types';
const mounted:Array<ReturnType<typeof mount>>=[];
afterEach(async()=>{for(const instance of mounted.splice(0))await unmount(instance);document.body.replaceChildren();document.documentElement.dir='ltr';});
const tags=[{name:'tag',label:'Tags',labelSingular:'Tag'}],link='https://blog.example.com/posts/example';
const term=(id='tag-1',label='Internship Experience',locale='en'):BulkTaxonomyTerm=>({id,label,locale,translationGroup:id,children:[]});
const entry={collection:'posts',id:'post-1',title:'Internship experience',locale:'en'};
async function fixture(options:{activeLocale?:string;defaultLocale?:string;adminLocale?:string;taxonomies?:typeof tags;failTerms?:boolean;failApply?:boolean;failCache?:boolean;unmatchedSecond?:boolean;selected?:typeof entry[]}={}){
 const state={failTerms:!!options.failTerms,failApply:!!options.failApply,failCache:!!options.failCache,unmatchedSecond:!!options.unmatchedSecond,created:false};
 const requests:Array<{termId:string;items:unknown[];apply:boolean;refreshOnly?:boolean}>=[];
 const client:BulkTaxonomyClient={terms:vi.fn(async(_name,opts)=>{if(state.failTerms)throw new Error('Unavailable');return[term(opts.locale==='fr'?'tag-1-fr':'tag-1',opts.locale==='fr'?'Expérience de stage':'Internship Experience',opts.locale),...(state.created?[term('tag-2','تجربة التدريب','ar')]:[])];}),createTerm:vi.fn(async(_name,input)=>{state.created=true;return term('tag-2',input.label,input.locale);}),bulkTag:vi.fn(async(termId,items,apply=false,refreshOnly=false)=>{requests.push({termId,items,apply,...(refreshOnly?{refreshOnly:true}:{})});return{results:items.map((input,index)=>({input,entry:index?{...entry,id:'post-2',title:'Second'}:entry,status:state.unmatchedSecond&&apply&&index===1?'unmatched':index>0&&'url'in input&&'url'in items[0]&&input.url===items[0].url?'skipped':apply?state.failApply?'failed':refreshOnly?'skipped':'added':'ready'} as BulkTaxonomyResult)),cacheRefreshFailed:apply&&state.failCache};})};
 const target=document.createElement('div');document.body.append(target);const instance=flushSync(()=>mount(Dialog,{target,props:{...options,taxonomies:options.taxonomies??tags,client,open:true,onClose:vi.fn()}}));mounted.push(instance);
 await vi.waitFor(()=>expect(client.terms).toHaveBeenCalled());await tick();
 const button=(name:string)=>Array.from(target.querySelectorAll<HTMLButtonElement>('button')).find(x=>x.textContent?.trim()===name||x.getAttribute('aria-label')===name);
 const click=async(name:string)=>{button(name)?.click();await tick();await Promise.resolve();await tick();};
 const field=(name:string)=>target.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`[aria-label=${JSON.stringify(name)}]`);
 const fill=async(name:string,value:string)=>{const node=field(name);if(node){node.value=value;node.dispatchEvent(new Event(node.tagName==='SELECT'?'change':'input',{bubbles:true}));}await tick();};
 const prepare=async()=>{await fill('Tag','tag-1');await fill('Post URLs (one per line)',link);await click('Review posts');};
 return{target,instance,client,state,requests,button,click,fill,field,prepare};
}
it('reviews exact title and locale and applies only the reviewed identity',async()=>{const f=await fixture();await f.prepare();expect(f.target.textContent).toContain(entry.title);expect(f.target.textContent).toContain('Tags go live now; draft edits stay unpublished.');expect(f.requests).toEqual([{termId:'tag-1',items:[{url:link}],apply:false}]);await f.click('Add tag to 1 post');expect(f.target.textContent).toContain('Added');expect(f.requests[1]).toEqual({termId:'tag-1',items:[{collection:'posts',id:'post-1'}],apply:true});});
it('switches the chosen taxonomy and uses its singular label',async()=>{const f=await fixture({taxonomies:[...tags,{name:'genre',label:'Genres',labelSingular:'Genre'}]});await f.fill('Taxonomy','genre');await Promise.resolve();await tick();expect(f.target.querySelector('h2')?.textContent).toBe('Add genre to posts');expect(f.client.terms).toHaveBeenLastCalledWith('genre',{locale:'en',includeCounts:false,resolveFallback:true});});
it('preserves selected term and pasted URLs when returning from review',async()=>{const f=await fixture();await f.prepare();await f.click('Back');expect(f.field('Post URLs (one per line)')?.value).toBe(link);expect(f.field('Tag')?.value).toBe('tag-1');await f.click('Review posts');expect(f.requests).toHaveLength(2);});
it('closes and resets before reopening without closed term fetches',async()=>{const f=await fixture();await f.fill('Post URLs (one per line)',link);f.instance.setOpen(false);await tick();expect(f.target.querySelector('[role="dialog"]')).toBeNull();f.instance.setOpen(true);await tick();expect(f.field('Post URLs (one per line)')?.value).toBe('');});
it('opens the real bulk dialog from selected native content rows',async()=>{const f=await fixture();await unmount(mounted.pop()!);f.target.replaceChildren();const instance=flushSync(()=>mount(Selection,{target:f.target,props:{collection:'posts',collectionLabel:'Posts',items:[{...entry,locale:'fr'}],taxonomies:tags,client:f.client,activeLocale:'fr',defaultLocale:'en'}}));mounted.push(instance);const check=f.target.querySelector<HTMLInputElement>('[aria-label="Select Internship experience"]');check?.click();await tick();await f.click('Add tag');expect(f.target.querySelector('[role="dialog"]')?.textContent).toContain('fr');expect(f.requests).toHaveLength(0);await f.fill('Tag','tag-1-fr');await f.click('Review posts');expect(f.requests[0]).toEqual({termId:'tag-1-fr',items:[{collection:'posts',id:'post-1'}],apply:false});});
it('retries failed writes without repeating successful review',async()=>{const f=await fixture({failApply:true});await f.prepare();await f.click('Add tag to 1 post');expect(f.target.textContent).toContain('Failed');f.state.failApply=false;await f.click('Retry failures');expect(f.target.textContent).toContain('Added');expect(f.requests.map(x=>x.apply)).toEqual([false,true,true]);});
it('keeps duplicate URL rows while applying each reviewed entry once',async()=>{const f=await fixture();await f.fill('Tag','tag-1');await f.fill('Post URLs (one per line)',`${link}\n${link}`);await f.click('Review posts');await f.click('Add tag to 1 post');expect(f.target.textContent).toContain('Already assigned or duplicate');expect(f.requests).toHaveLength(2);expect(f.requests[1].items).toEqual([{collection:'posts',id:'post-1'}]);});
it('creates and selects a new localized term in RTL',async()=>{document.documentElement.dir='rtl';const f=await fixture({defaultLocale:'ar'});await f.click('Create new tag');await f.fill('New tag name','تجربة التدريب');await f.click('Create tag');await f.fill('Post URLs (one per line)',link);await f.click('Review posts');expect(f.client.createTerm).toHaveBeenCalledWith('tag',{label:'تجربة التدريب',locale:'ar'});expect(f.requests[0]?.termId).toBe('tag-2');});
it('preserves German noun capitalization',async()=>{const f=await fixture({adminLocale:'de',taxonomies:[{name:'tag',label:'Schlagwörter',labelSingular:'Schlagwort'}]});expect(f.target.textContent).toContain('Add Schlagwort to posts');expect(f.target.textContent).toContain('Existing Schlagwörter stay in place.');expect(f.button('Create new Schlagwort')).toBeDefined();});
it('uses configured term locale without unused counts',async()=>{const f=await fixture({defaultLocale:'fr'});expect(f.client.terms).toHaveBeenCalledWith('tag',{locale:'fr',includeCounts:false,resolveFallback:true});await f.fill('Tag','tag-1-fr');await f.fill('Post URLs (one per line)',link);await f.click('Review posts');expect(f.requests[0]?.termId).toBe('tag-1-fr');});
it('prefers active content locale for fetch and creation',async()=>{const f=await fixture({activeLocale:'fr',defaultLocale:'en'});await f.click('Create new tag');await f.fill('New tag name','Nouvelle étiquette');await f.click('Create tag');expect(f.client.terms).toHaveBeenCalledWith('tag',{locale:'fr',includeCounts:false,resolveFallback:true});expect(f.client.createTerm).toHaveBeenCalledWith('tag',{label:'Nouvelle étiquette',locale:'fr'});});
it('shows term failures and disables duplicate creation until retry succeeds',async()=>{const f=await fixture({failTerms:true});expect(f.target.querySelector('[role="alert"]')?.textContent).toBe('Could not load tags.');expect(f.button('Create new tag')?.disabled).toBe(true);f.state.failTerms=false;await f.click('Retry loading tags');expect(f.target.querySelector('[role="alert"]')).toBeNull();expect(f.field('Tag')?.textContent).toContain('Internship Experience');});
it('retries committed cache failures without changing an Added result',async()=>{const f=await fixture({failCache:true});await f.prepare();await f.click('Add tag to 1 post');expect(f.target.textContent).toContain('cached pages may still show old tags');f.state.failCache=false;await f.click('Retry cache refresh');expect(f.target.textContent).toContain('Added');expect(f.target.textContent).not.toContain('cached pages may still show old tags');expect(f.requests.at(-1)).toEqual({termId:'tag-1',items:[{collection:'posts',id:'post-1'}],apply:true,refreshOnly:true});});
it('cache-only retry excludes unmatched rows while preserving reviewed titles',async()=>{const f=await fixture({failCache:true,unmatchedSecond:true});await f.fill('Tag','tag-1');await f.fill('Post URLs (one per line)',`${link}\n${link}-second`);await f.click('Review posts');await f.click('Add tag to 2 posts');expect(f.target.textContent).toContain('Second');expect(f.target.textContent).toContain('Not matched');f.state.failCache=false;await f.click('Retry cache refresh');expect(f.requests.at(-1)?.items).toEqual([{collection:'posts',id:'post-1'}]);});
