// Deterministic Native English fallback arrays; generated by frozen Lingui5.9.5.
// Exact source descriptors remain in message-descriptors.ts; no catalog is activated.
export const CALENDAR_MESSAGE_FALLBACKS = {
  "{0, plural, one {# entry} other {# entries}}": [
    [
      "0",
      "plural",
      {
        "one": [
          "#",
          " entry"
        ],
        "other": [
          "#",
          " entries"
        ]
      }
    ]
  ],
  "{dayLabel}, {entries}": [
    [
      "dayLabel"
    ],
    ", ",
    [
      "entries"
    ]
  ],
  "{earlierCount, plural, one {Show # earlier entry} other {Show # earlier entries}}": [
    [
      "earlierCount",
      "plural",
      {
        "one": [
          "Show ",
          "#",
          " earlier entry"
        ],
        "other": [
          "Show ",
          "#",
          " earlier entries"
        ]
      }
    ]
  ],
  "{hidden, plural, one {# more entry on {date}} other {# more entries on {date}}}": [
    [
      "hidden",
      "plural",
      {
        "one": [
          "#",
          " more entry on ",
          [
            "date"
          ]
        ],
        "other": [
          "#",
          " more entries on ",
          [
            "date"
          ]
        ]
      }
    ]
  ],
  "{hidden, plural, one {+# more} other {+# more}}": [
    [
      "hidden",
      "plural",
      {
        "one": [
          "+",
          "#",
          " more"
        ],
        "other": [
          "+",
          "#",
          " more"
        ]
      }
    ]
  ],
  "{lateness} late": [
    [
      "lateness"
    ],
    " late"
  ],
  "{siteZone} · Your time: {viewerZone}": [
    [
      "siteZone"
    ],
    " · Your time: ",
    [
      "viewerZone"
    ]
  ],
  "{state} · {when}": [
    [
      "state"
    ],
    " · ",
    [
      "when"
    ]
  ],
  "{state}, {time}:": [
    [
      "state"
    ],
    ", ",
    [
      "time"
    ],
    ":"
  ],
  "{title} is a draft again.": [
    [
      "title"
    ],
    " is a draft again."
  ],
  "{title} is now live.": [
    [
      "title"
    ],
    " is now live."
  ],
  "{title} now goes live {when}.": [
    [
      "title"
    ],
    " now goes live ",
    [
      "when"
    ],
    "."
  ],
  "Agenda": [
    "Agenda"
  ],
  "Bylines": [
    "Bylines"
  ],
  "Calendar": [
    "Calendar"
  ],
  "Cancel": [
    "Cancel"
  ],
  "Change schedule": [
    "Change schedule"
  ],
  "Check your connection and try again.": [
    "Check your connection and try again."
  ],
  "Choose a new publication time for this draft.": [
    "Choose a new publication time for this draft."
  ],
  "Choose when these changes replace the live version.": [
    "Choose when these changes replace the live version."
  ],
  "Choose when this draft becomes public.": [
    "Choose when this draft becomes public."
  ],
  "Clear filters": [
    "Clear filters"
  ],
  "Close": [
    "Close"
  ],
  "Collection": [
    "Collection"
  ],
  "Could not load the calendar": [
    "Could not load the calendar"
  ],
  "Could not load this entry's details.": [
    "Could not load this entry's details."
  ],
  "Could not publish": [
    "Could not publish"
  ],
  "Could not remove the schedule": [
    "Could not remove the schedule"
  ],
  "Draft": [
    "Draft"
  ],
  "Filter": [
    "Filter"
  ],
  "Filter: {activeCount} selected": [
    "Filter: ",
    [
      "activeCount"
    ],
    " selected"
  ],
  "Go live {countdown}": [
    "Go live ",
    [
      "countdown"
    ]
  ],
  "Goes live": [
    "Goes live"
  ],
  "Goes live {countdown}": [
    "Goes live ",
    [
      "countdown"
    ]
  ],
  "Hide earlier entries": [
    "Hide earlier entries"
  ],
  "Last edited": [
    "Last edited"
  ],
  "Later entries weren't loaded. The range has more entries than the calendar can show.": [
    "Later entries weren't loaded. The range has more entries than the calendar can show."
  ],
  "Live version": [
    "Live version"
  ],
  "Loading": [
    "Loading"
  ],
  "Locale": [
    "Locale"
  ],
  "Month": [
    "Month"
  ],
  "Next month": [
    "Next month"
  ],
  "No entries match these filters": [
    "No entries match these filters"
  ],
  "No loaded entries match these filters": [
    "No loaded entries match these filters"
  ],
  "Not loaded": [
    "Not loaded"
  ],
  "Nothing else is scheduled this month.": [
    "Nothing else is scheduled this month."
  ],
  "Nothing on this day.": [
    "Nothing on this day."
  ],
  "Nothing published or scheduled in {monthTitle}": [
    "Nothing published or scheduled in ",
    [
      "monthTitle"
    ]
  ],
  "Now · {time}": [
    "Now · ",
    [
      "time"
    ]
  ],
  "Open in editor": [
    "Open in editor"
  ],
  "Overdue": [
    "Overdue"
  ],
  "Overdue · {lateness}": [
    "Overdue · ",
    [
      "lateness"
    ]
  ],
  "Preview": [
    "Preview"
  ],
  "Preview changes": [
    "Preview changes"
  ],
  "Previous month": [
    "Previous month"
  ],
  "Publish now": [
    "Publish now"
  ],
  "Published": [
    "Published"
  ],
  "Published {liveSince}": [
    "Published ",
    [
      "liveSince"
    ]
  ],
  "Published and scheduled entries across collections, in the site's time zone.": [
    "Published and scheduled entries across collections, in the site's time zone."
  ],
  "Publishing": [
    "Publishing"
  ],
  "Remove schedule": [
    "Remove schedule"
  ],
  "Reschedule": [
    "Reschedule"
  ],
  "Rescheduled": [
    "Rescheduled"
  ],
  "Retry": [
    "Retry"
  ],
  "Save schedule": [
    "Save schedule"
  ],
  "Schedule": [
    "Schedule"
  ],
  "Schedule changes": [
    "Schedule changes"
  ],
  "Schedule date": [
    "Schedule date"
  ],
  "Schedule publication": [
    "Schedule publication"
  ],
  "Schedule removed": [
    "Schedule removed"
  ],
  "Scheduled": [
    "Scheduled"
  ],
  "Scheduled changes": [
    "Scheduled changes"
  ],
  "Scheduled entries appear here with their publish time.": [
    "Scheduled entries appear here with their publish time."
  ],
  "State": [
    "State"
  ],
  "The calendar shows the first {maxEntries}, which end on {cutOffDay}.": [
    "The calendar shows the first ",
    [
      "maxEntries"
    ],
    ", which end on ",
    [
      "cutOffDay"
    ],
    "."
  ],
  "The calendar shows the first {maxEntries}.": [
    "The calendar shows the first ",
    [
      "maxEntries"
    ],
    "."
  ],
  "The range has more entries than the calendar can show.": [
    "The range has more entries than the calendar can show."
  ],
  "The scheduled changes to {title} stay as a draft.": [
    "The scheduled changes to ",
    [
      "title"
    ],
    " stay as a draft."
  ],
  "This day wasn't loaded. The range has more entries than the calendar can show.": [
    "This day wasn't loaded. The range has more entries than the calendar can show."
  ],
  "This entry was due {lateness} but hasn't published. Scheduled publishing may not be running.": [
    "This entry was due ",
    [
      "lateness"
    ],
    " but hasn't published. Scheduled publishing may not be running."
  ],
  "This month wasn't loaded": [
    "This month wasn't loaded"
  ],
  "This range has more than {maxEntries} entries": [
    "This range has more than ",
    [
      "maxEntries"
    ],
    " entries"
  ],
  "Times are in {zoneName}.": [
    "Times are in ",
    [
      "zoneName"
    ],
    "."
  ],
  "Times are in {zoneName}. Your browser uses {viewerZoneName}.": [
    "Times are in ",
    [
      "zoneName"
    ],
    ". Your browser uses ",
    [
      "viewerZoneName"
    ],
    "."
  ],
  "Today": [
    "Today"
  ],
  "Tomorrow": [
    "Tomorrow"
  ],
  "Translations:": [
    "Translations:"
  ],
  "Update": [
    "Update"
  ],
  "Update scheduled": [
    "Update scheduled"
  ],
  "View live": [
    "View live"
  ],
  "Was due": [
    "Was due"
  ],
  "You don't have permission to view the calendar.": [
    "You don't have permission to view the calendar."
  ],
  "Your time: {viewerTime}": [
    "Your time: ",
    [
      "viewerTime"
    ]
  ],
  "An error occurred": [
    "An error occurred"
  ]
} as const;
